# Test-specific configuration
random_seed = 9999
simulation_period_days = 100
time_step_minutes = 60

[[asset_models]]
asset_type = "stock"
asset_identifier_pattern = "TEST_DEFAULT" # For testing config-based stock sims
default_model = "GeometricBrownianMotion"
[asset_models.parameters.gbm]
drift = 0.03
volatility = 0.15

[[asset_models]]
asset_type = "stock"
asset_identifier_pattern = "TEST_OVERRIDE" # For testing parameter overrides
default_model = "GeometricBrownianMotion"
[asset_models.parameters.gbm]
drift = 0.06
volatility = 0.25
